### ISSUE TITLE
Código en root del proyecto

### ISSUE THREAD

**Issue by yosoyfunes** [holamugar/module-customer-identification-document#7]
Tendríamos que tener el código de **app/code** en el root del proyecto con el fin de poder utilizarlo por composer.
`app/code/Mugar/CustomerIdentificationDocument`

también necesitamos el archivo `composer.json` con los datos para poder utilizarlo en [packagist.org](https://packagist.org/)

**ejemplo**
```
{
  "name": "mugar/module-customer-identification-document",
  "description": "Customer Identification Module",
  "type": "magento2-module",
  "version": "1.0.0",
  "require": {
    "php": "~7.1.0|~7.2.0"
  },
  "license": [
    "OSL-3.0",
    "AFL-3.0"
  ],
  "autoload": {
    "files": [ "registration.php" ],
    "psr-4": {
      "Mugar\\CustomerIdentificationDocument\\": ""
    }
  }
}
```

**Comment by manuelcanepa** [comment]
Se podria agregar mejor en un directorio `src` para contemplar la posibilidad de incorporar tests

**Comment by barbanet** [comment]
Los Tests tienen directorio: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/module-file-structure.html#module-file-structure
